name: TOP10SONG

on:
  workflow_dispatch:
  push:
   branches: [ main ]
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
         matrix:
             os: [self-hosted-1, self-hosted-2]

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "mdshahidahmad" --password-stdin
        docker image build -t mdshahidahmad/top10song:v1 .
        docker push mdshahidahmad/top10song:v1
