name: TOP10SONG

on:
  workflow_dispatch:
  push:
   branches: [ main ]
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
         matrix:
             os: [ubuntu-latest, ubuntu-latest]

    steps:
      - name: Group of log lines
        run: |
            echo "The sysbeanch test script need to learn if needed"
            echo "Didn't work yet with sysbeanch"
