name: TOP10SONG

on:
  workflow_dispatch:
  push:
   branches: [ main ]
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
         matrix:
             os: [ubuntu-latest, ubuntu-latest]

    steps:
      - name: Group of log lines
        run: |
            sysbench --test=cpu --time=60 run
            echo "Inside group"
            echo "::endgroup::"
